# Generated by Django 3.2.1 on 2023-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking', '0009_alter_customuser_managers_alter_gymmembership_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymmembership',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='gymmembership',
            name='expiry_date',
            field=models.DateTimeField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='gymmembership',
            name='plan',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='bronze', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(max_length=50),
        ),
    ]
