# Generated by Django 3.2.1 on 2023-12-21 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking', '0011_payment_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='gym_booking.gymmembership'),
        ),
    ]
