# Generated by Django 3.2.1 on 2023-12-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking', '0014_auto_20231222_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='.....', max_length=10),
        ),
    ]
