# Generated by Django 3.2.1 on 2023-12-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_booking', '0020_remove_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='plan',
            field=models.CharField(blank=True, choices=[('No Plan', 'No Plan'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='No Plan', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], default='No Plan', max_length=10, null=True),
        ),
    ]
