# Generated by Django 3.2.1 on 2023-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_pitch', '0002_rename_minutes_payment_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ref',
            field=models.CharField(max_length=50),
        ),
    ]
